name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build git qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libssl-dev libsodium-dev libargon2-dev

      - name: Install Homebrew (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || { echo "Homebrew installation failed"; exit 1; }

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install qt@5 openssl libsodium argon2 ninja
          brew link --force qt@5

      - name: Set environment variables for macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "ARGON2_LIB_DIR=$(brew --prefix argon2)/lib" >> $GITHUB_ENV
          echo "ARGON2_INCLUDE_DIR=$(brew --prefix argon2)/include" >> $GITHUB_ENV
          echo "SODIUM_LIB_DIR=$(brew --prefix libsodium)/lib" >> $GITHUB_ENV
          echo "SODIUM_INCLUDE_DIR=$(brew --prefix libsodium)/include" >> $GITHUB_ENV

      - name: Configure CMake (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          QT_DIR=$(brew --prefix qt@5)
          cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH=$QT_DIR -DQt5_DIR=$QT_DIR/lib/cmake/Qt5 -DQt5Core_DIR=$QT_DIR/lib/cmake/Qt5Core -DQt5Gui_DIR=$QT_DIR/lib/cmake/Qt5Gui -DQt5Widgets_DIR=$QT_DIR/lib/cmake/Qt5Widgets

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: cmake --build build --config Release

      - name: Install Chocolatey (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          iex "& { $(irm https://chocolatey.org/install.ps1 -UseBasicP) }"

      - name: Install MinGW (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw --version 8.1.0 -y

      - name: Check MinGW Installation (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          g++ --version

      - name: Install CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v3.21.2/cmake-3.21.2-windows-x86_64.zip" -OutFile "cmake.zip"
          Expand-Archive -Path "cmake.zip" -DestinationPath "C:\cmake"
          [System.Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\cmake\bin", [System.EnvironmentVariableTarget]::Machine)

      - name: Install Qt (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://qt.mirror.constant.com/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip" -OutFile "qt-installer.zip"
          Expand-Archive -Path "qt-installer.zip" -DestinationPath "C:\Qt"
          [System.Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\Qt\5.15.2\mingw81_64\bin", [System.EnvironmentVariableTarget]::Machine)
      
      - name: Install OpenSSL (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://slproweb.com/download/Win64OpenSSL-1_1_1k.exe" -OutFile "openssl.exe"
          Start-Process "openssl.exe" -ArgumentList "/S" -NoNewWindow -Wait

      - name: Install libsodium (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip" -OutFile "libsodium.zip"
          Expand-Archive -Path "libsodium.zip" -DestinationPath "C:\libsodium"

      - name: Install Argon2 (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://github.com/P-H-C/phc-winner-argon2/archive/refs/heads/master.zip" -OutFile "argon2.zip"
          Expand-Archive -Path "argon2.zip" -DestinationPath .
          cd phc-winner-argon2-master
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          cmake --build . --config Release
          Copy-Item -Path "Release\libargon2.a" -Destination "C:\argon2"
          Copy-Item -Path "..\include" -Destination "C:\argon2"

      - name: Set environment variables for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "ARGON2_LIB_DIR=C:\argon2" >> $env:GITHUB_ENV
          echo "ARGON2_INCLUDE_DIR=C:\argon2\include" >> $env:GITHUB_ENV
          echo "SODIUM_LIB_DIR=C:\libsodium" >> $env:GITHUB_ENV
          echo "SODIUM_INCLUDE_DIR=C:\libsodium\include" >> $env:GITHUB_ENV

      - name: Configure CMake
        run: cmake -S . -B build -G "${{ matrix.os == 'windows-latest' && 'MinGW Makefiles' || 'Ninja' }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-build
          path: builds/linux/

      - name: Download build artifacts (macOS)
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-build
          path: builds/macos/

      - name: Download build artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-build
          path: builds/windows/

      - name: Create release directory
        run: mkdir -p release

      - name: Copy build artifacts to release directory
        run: |
          cp -r builds/linux release/linux
          cp -r builds/macos release/macos
          cp -r builds/windows release/windows

      - name: Create zip of source code
        run: zip -r release/source.zip . -x .git\*

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release assets to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/
          asset_name: release.zip
          asset_content_type: application/zip
